### ISSUE TITLE
"Finished" button appears for other players despite not being their turn

### ISSUE THREAD

**Issue by mmmegaidiot** [jyoung4242/ds-proto#13]
I need to snag a screenshot, but it _can_ happen, not sure if pressing the button can end a turn, will need to experiment with that

**Comment by mmmegaidiot** [comment]
i can confirm that turns don't end, but the button still remains

here, i have timmy, another "player" in a match

(it's his turn, it should be available in the menu)

![image](https://user-images.githubusercontent.com/76692588/195964623-d088d3ae-c64a-4b75-801d-2c825b5a219b.png)

here's my screen in comparision

(it's _not_ my turn yet)

![image](https://user-images.githubusercontent.com/76692588/195964683-557ae17d-32c6-4460-aacc-8e15d55ee948.png)

something's off, but at least nobody else can end a person's turn

**Comment by jyoung4242** [comment]
fixed in 0.1.5
